source 'https://rubygems.org'

gem 'berkshelf'
gem 'chef', '~> 11.8'
gem 'rake'
gem 'rubocop', '~> 0.18'
gem 'foodcritic', '~> 3.0'
gem 'chefspec', '~> 3.2'
gem 'serverspec', '~> 0.14'
gem 'test-kitchen'
gem 'kitchen-vagrant'
gem 'kitchen-rackspace'
gem 'guard', '~> 1.8'
gem 'guard-rubocop', '~> 0.2'
gem 'guard-foodcritic', '~> 1.0.2'
